#!/usr/bin/python2
# coding=utf-8

# Base Python 2 File (%PLACE_FILENAME%)
# Created: %PLACE_CREATETIME%
# Version: 1.0
#
# This Python 2 script was developped by François-Xavier Thomas.
# You are free to copy, adapt or modify it.
# If you do so, however, leave my name somewhere in the credits, I'd appreciate it ;)
# 
# (ɔ) François-Xavier Thomas <fx.thomas@gmail.com>

%PLACE_CURSOR%
